### ISSUE TITLE
Where is the folder ink \ main.h - inc. and all 

### ISSUE THREAD

**Issue by EliXorZz** [DireDan/Sanctified-Base#1]
Thank you for remedying this problem

**Comment by DireDan** [comment]
Oh when I initially uploaded this, I did it through Visual Studio's shite, and due to how the ScriptHookV SDK is organized, it didn't pick them all up...

I'll try and correct this now

**Comment by DireDan** [comment]
https://github.com/DireDan/Sanctified-Base/commit/93e251e63e4a8d9815366ef201b84f85bdc20565
